src/Entity/Rentail.php
<?php

namespace App\Entity;

use App\Repository\RentailRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=RentailRepository::class)
 */
class Rentail
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Car::class, inversedBy="rentails")
     * @Assert\NotBlank
     */
    private $car;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="rentails")
     * @Assert\NotBlank
     */
    private $client;



    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     */
    private $date_rentail;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_devolution;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDateRentail(): ?\DateTimeInterface
    {
        return $this->date_rentail;
    }

    public function setDateRentail(?\DateTimeInterface $date_rentail): self
    {
        $this->date_rentail = $date_rentail;

        return $this;
    }

    public function getDateDevolution(): ?\DateTimeInterface
    {
        return $this->date_devolution;
    }

    public function setDateDevolution(?\DateTimeInterface $date_devolution): self
    {
        $this->date_devolution = $date_devolution;

        return $this;
    }

   

}

src/Form/RentailType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Client;
use App\Entity\Rentail;
use App\Repository\CarRepository;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class RentailType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // $builder
        //     ->add('date_rentail',  DateType::class, [
        //         'label' => 'Data de Locação',
        //        'widget' => 'single_text',
        //     ])
        //     ->add('car',  EntityType::class, [
        //         'class' => Car::class,
        //         'query_builder' => function (CarRepository $er) {
        //             return $er->createQueryBuilder('c')
        //                 ->where('c.status = 0');
        //         },
        //         'choice_label' => function ($car) {
        //             return  $car->getBrand()->getName() . ' ' . $car->getModel() . ' - ' . $car->getYear();
        //         },
        //         'label' => 'Carro'
        //     ])
        //     ->add('client', EntityType::class, [
        //         'class' => Client::class,
        //         'choice_label' => 'name',
        //         'label' => 'Cliente'
        //     ])
        // ;

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $rentail = $event->getData();
            $form = $event->getForm();

        
    
            // // checks if the Product object is "new"
            // // If no data is passed to the form, the data is "null".
            // // This should be considered a new "Product"
            if ($rentail && $rentail->getId()) {

                $form->add('date_devolution',  DateType::class, [
                'label' => 'Data de devolução',
                'widget' => 'single_text',
                'constraints' => [ new NotBlank()]
                ]);
            }  else {
                $form->add('date_rentail',  DateType::class, [
                    'label' => 'Data de Locação',
                   'widget' => 'single_text',
                ])
                ->add('car',  EntityType::class, [
                    'class' => Car::class,
                    'query_builder' => function (CarRepository $er) {
                        return $er->createQueryBuilder('c')
                            ->where('c.status = 0');
                    },
                    'choice_label' => function ($car) {
                        return  $car->getBrand()->getName() . ' ' . $car->getModel() . ' - ' . $car->getYear();
                    },
                    'label' => 'Carro'
                ])
                ->add('client', EntityType::class, [
                    'class' => Client::class,
                    'choice_label' => 'name',
                    'label' => 'Cliente'
                ]);

            }

          
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rentail::class,
        ]);
    }
}

src/Controller/RentailController.php
<?php

namespace App\Controller;

use App\Entity\Rentail;
use App\Form\RentailType;
use App\Repository\RentailRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/rentail")
 * @Security("is_authenticated()")
 */
class RentailController extends AbstractController
{
    /**
     * @Route("/", name="rentail_index", methods={"GET"})
     */
    public function index(RentailRepository $rentailRepository): Response
    {
        return $this->render('rentail/index.html.twig', [
            'rentails' => $rentailRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="rentail_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rentail = new Rentail();
        $form = $this->createForm(RentailType::class, $rentail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $car = $rentail->getCar();
            $car->setStatus(true);
            $rentail->setCar($car);
            $entityManager->persist($rentail);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Cadastro concluido com sucesso'
            );
            return $this->redirectToRoute('rentail_index');
        }

        return $this->render('rentail/new.html.twig', [
            'rentail' => $rentail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rentail_show", methods={"GET"})
     */
    public function show(Rentail $rentail): Response
    {
        return $this->render('rentail/show.html.twig', [
            'rentail' => $rentail,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rentail_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Rentail $rentail): Response
    {
        $form = $this->createForm(RentailType::class, $rentail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $car = $rentail->getCar();
            $car->setStatus(false);
            $rentail->setCar($car);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash(
                'success',
                'Alteração concluida com sucesso'
            );
            return $this->redirectToRoute('rentail_index');
        }

        return $this->render('rentail/edit.html.twig', [
            'rentail' => $rentail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rentail_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Rentail $rentail): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rentail->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $car = $rentail->getCar();
            $car->setStatus(false);
            $rentail->setCar($car);
            $entityManager->remove($rentail);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rentail_index');
    }
}

templates/rentail/_delete_form.html.twig
<form method="post" action="{{ path('rentail_delete', {'id': rentail.id}) }}" onsubmit="return confirm('Você realmente quer apagar este item?');" class="float-right">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rentail.id) }}">
    <button class="btn btn-danger ">Remover</button>
</form>

templates/rentail/_form.html.twig
<div class="card">
    <div class="card-body">

{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {# {{ form_widget(form) }} #}
    {% if not rentail.getId()   %}
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.car) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.client) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.date_rentail) }}
                </div>
            </div>
     {% else  %}
            <table class="table">
                <tbody>
                    <tr>
                        <th>Carro</th>
                        <td>{{ rentail.getCar().getBrand().name }} {{ rentail.getCar().model }} {{ rentail.getCar().getYear() }}</td>
                    </tr>
                    <tr>
                        <th>Cliente</th>
                        <td>{{ rentail.getClient().name }}</td>
                    </tr>
                    <tr>
                        <th>Data de Locação</th>
                        <td>{{ rentail.dateRentail ? rentail.dateRentail|date('d-m-Y') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td><span class="badge badge-{{ (rentail.getCar().status) ? 'warning' : 'success' }}"> {{ (rentail.getCar().status) ? 'Locado' : 'Devolvida' }}</span></td>
                    </tr>
                </tbody>
            </table>
            {% if form.date_devolution is defined %}
                <div class="col-md-6">
                    {{ form_row(form.date_devolution) }}
                </div>
            {% endif %}

     {% endif %}
    <button class="btn btn-success float-right">{{ button_label|default('Salvar') }}</button>
{{ form_end(form) }}
    <a href="{{ path('rentail_index') }}">voltar para listagem</a>

    </div>
</div>

templates/rentail/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Devolução Locação{% endblock %}

{% block content %}
    <h1>Devolução</h1>
    <hr/>

    {{ include('rentail/_form.html.twig', {'button_label': 'Devolver Carro'}) }}


    {# {{ include('rentail/_delete_form.html.twig') }} #}
{% endblock %}

templates/rentail/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Lista de Locações{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <h1 class="text-uppercase">Lista de Locações</h1>
        </div>
        <div class="col-6">
             <a href="{{ path('rentail_new') }} " class="btn btn-primary float-right">Locar Carro</a>
        </div>
    </div>  

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">  
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>Id</th>
                            <th>Carro</th>
                            <th>Cliente</th>
                            <th>Data Locação</th>
                            <th>Data Devolução</th>
                            <th>Status</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for rentail in rentails %}
                        <tr>
                            <td>{{ rentail.id }}</td>
                            <td>{{ rentail.getCar().getBrand().name }} {{ rentail.getCar().model }} {{ rentail.getCar().getYear() }}</td>
                            <td>{{ rentail.getClient().name }}</td>
                            <td>{{ rentail.dateRentail ? rentail.dateRentail|date('d-m-Y') : '' }}</td>
                            <td>{{ rentail.dateDevolution ? rentail.dateDevolution|date('d-m-Y') : '' }}</td>
                            <td>
                                 <span class="badge badge-{{ (rentail.getCar().status) ? 'warning' : 'success' }}"> {{ (rentail.getCar().status) ? 'Locado' : 'Devolvida' }}</span>
                           </td>
                            <td>
                                <a class="btn btn-success" href="{{ path('rentail_show', {'id': rentail.id}) }}">Mostrar</a>
                                {% if  rentail.dateDevolution  == '' %}
                                <a class="btn btn-primary" href="{{ path('rentail_edit', {'id': rentail.id}) }}">Devolver</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
   
{% endblock %}

templates/rentail/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Nova Locação{% endblock %}

{% block content %}
    <h1>Nova Locação</h1>
    <hr/>

    {{ include('rentail/_form.html.twig') }}

{% endblock %}

templates/rentail/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Rentail{% endblock %}

{% block content %}
    <h1>Locação</h1>

<div class="card">
    <div class="card-body">
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ rentail.id }}</td>
                </tr>
                <tr>
                    <th>Carro</th>
                    <td>{{ rentail.getCar().getBrand().name }} {{ rentail.getCar().model }} {{ rentail.getCar().getYear() }}</td>
                </tr>
                <tr>
                    <th>Cliente</th>
                    <td>{{ rentail.getClient().name }}</td>
                </tr>
                <tr>
                    <th>Data de Locação</th>
                    <td>{{ rentail.dateRentail ? rentail.dateRentail|date('d-m-Y') : '' }}</td>
                </tr>
                <tr>
                    <th>Data de Devolução</th>
                    <td>{{ rentail.dateDevolution ? rentail.dateDevolution|date('d-m-Y') : '' }}</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        <span class="badge badge-{{ (rentail.getCar().status) ? 'warning' : 'success' }}"> {{ (rentail.getCar().status) ? 'Locado' : 'Devolvida' }}</span>
                    </td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('rentail_index') }}">Voltar para listagem</a>

        {% if  rentail.dateDevolution  == '' %}
            <a href="{{ path('rentail_edit', {'id': rentail.id}) }}" class="btn btn-primary float-right ml-3">Devolver</a>
        {% endif %}

        {{ include('rentail/_delete_form.html.twig') }}
    </div>
</div>        
{% endblock %}